

try{
    myFunc()

} catch (error){
    console.log(error)
}

