
// function myFunc() {
//     try{
//         //the throw statement allows you to create a custom error
//         throw "hey stop that!"
        
//     } catch (error){
//         //this error will refer back to my custom error in my try block 
//         console.log(error)
//     }
// }

// try{
//     let x = 3
//     throw x
// } catch (e){
//     console.log(e)
// }


let x = 5
let y = "4"
let z = x+parseInt(y)

console.log(z)




